apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: 0932631194/kubernetesbe:v2.0
          ports:
            - containerPort: 8080
          env:
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100